 <!--navigation-->
    <nav class="topnav" id="myTopnav">
            <a href="index.html" class="active">Home</a>
            <a href="about.html">link2</a>
            <a href="design.html">Link 3</a>
            <a href="development.html">Link 4</a>
            <a href="contact.html">Contact</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
    </nav